FROM debezium/connect:1.4

USER root

# Install wget and unzip
RUN yum install -y wget unzip && yum clean all

# Download and install Elasticsearch connector
RUN cd /tmp && \
    wget https://d2p6pa21dvn84.cloudfront.net/api/plugins/confluentinc/kafka-connect-elasticsearch/versions/11.1.3/confluentinc-kafka-connect-elasticsearch-11.1.3.zip && \
    unzip confluentinc-kafka-connect-elasticsearch-11.1.3.zip -d /kafka/connect/ && \
    rm confluentinc-kafka-connect-elasticsearch-11.1.3.zip

USER kafka
